### ISSUE TITLE
./rss2cloud: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./rss2cloud)

### ISSUE THREAD

**Issue by Volundio** [zhifengle/rss2cloud#2]
在centos7中直接使用rss2cloud无法运行，用.\rss2cloud运行后报错./rss2cloud: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./rss2cloud)

看了下centos7似乎最高只支持到2.17
https://p.sda1.dev/16/afeb737dcbef069b32d51c30e50d16d4/msedge_L26ATgnGx3.png
请问一下该软件一定需要这么高的glibc依赖吗

**Comment by zhifengle** [comment]
Linux 版本是使用的 Github Ubuntu latest 构建的，所以是依赖默认 glibc。
使用静态链接构建一下，先试试附件这个
[rss2cloud-v0.1.4-linux-amd64-musl.tar.gz](https://github.com/zhifengle/rss2cloud/releases/download/v0.1.4/rss2cloud-v0.1.4-linux-amd64-musl.tar.gz)

**Comment by Volundio** [comment]
> Linux 版本是使用的 Github Ubuntu latest 构建的，所以是依赖默认 glibc。 使用静态链接构建一下，先试试附件这个 [rss2cloud-v0.1.4-linux-amd64-musl.tar.gz](https://github.com/zhifengle/rss2cloud/releases/download/v0.1.4/rss2cloud-v0.1.4-linux-amd64-musl.tar.gz)

感谢，不过最后还是放弃折腾glibc，省的炸了老centos，重新开了一台小鸡跑这个服务了。
请问该项目，目前是否还没有自带 常驻后台定时rss功能？是需要自己开一个定时器定时启动rss2cloud吗？

**Comment by zhifengle** [comment]
> > Linux 版本是使用的 Github Ubuntu latest 构建的，所以是依赖默认 glibc。 使用静态链接构建一下，先试试附件这个 [rss2cloud-v0.1.4-linux-amd64-musl.tar.gz](https://github.com/zhifengle/rss2cloud/releases/download/v0.1.4/rss2cloud-v0.1.4-linux-amd64-musl.tar.gz)
> 
> 感谢，不过最后还是放弃折腾glibc，省的炸了老centos，重新开了一台小鸡跑这个服务了。 请问该项目，目前是否还没有自带 常驻后台定时rss功能？是需要自己开一个定时器定时启动rss2cloud吗？

 没有定时功能，可以使用 crontab

**Comment by Volundio** [comment]
> > > Linux 版本是使用的 Github Ubuntu latest 构建的，所以是依赖默认 glibc。 使用静态链接构建一下，先试试附件这个 [rss2cloud-v0.1.4-linux-amd64-musl.tar.gz](https://github.com/zhifengle/rss2cloud/releases/download/v0.1.4/rss2cloud-v0.1.4-linux-amd64-musl.tar.gz)
> > 
> > 
> > 感谢，不过最后还是放弃折腾glibc，省的炸了老centos，重新开了一台小鸡跑这个服务了。 请问该项目，目前是否还没有自带 常驻后台定时rss功能？是需要自己开一个定时器定时启动rss2cloud吗？
> 
> 没有定时功能，可以使用 crontab

感谢，但是在使用crontab过程中又遇到了问题。可以请教一下吗？

写入cookies文件后可以正常运行(0task是因为之前离线过了)
https://p.sda1.dev/17/679f17fbd73fbe323e1467617c8a6ad7/WindowsTerminal_my7UI7mVA9.png

但是用crontab无论是手动提交cookie还是调用cookies文件都出现了问题。


用crontab直接默认执行调用cookies文件的时候报错
https://p.sda1.dev/17/4d7b324745401f889150d8a76c3bd9f5/WindowsTerminal_F5z0a7wmkR.png
> 2024/04/17 13:00:01 .cookies is empty or not exist

用crontab手动提交cookie则报错
https://p.sda1.dev/17/0a81b16882be5c9b5f78bd4b4617b14a/WindowsTerminal_hf2eZHL0f4.png
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x855407]
> 
> goroutine 1 [running]:
> github.com/zhifengle/rss2cloud/p115.(*Agent).ExecuteAllRssTask(0xc00027e340)
> 	/github/workspace/p115/p115.go:160 +0x27
> github.com/zhifengle/rss2cloud/cmd.init.func1(0xc000126300?, {0xa08ff8?, 0x4?, 0xa08ffc?})
> 	/github/workspace/cmd/rss2cloud.go:40 +0xc5
> github.com/spf13/cobra.(*Command).execute(0xe14420, {0xc0000922b0, 0x2, 0x2})
> 	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
> github.com/spf13/cobra.(*Command).ExecuteC(0xe14420)
> 	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
> github.com/zhifengle/rss2cloud/cmd.Execute()
> 	/github/workspace/cmd/rss2cloud.go:71 +0x1a
> main.main()
> 	/github/workspace/main.go:8 +0xf



https://p.sda1.dev/17/0a81b16882be5c9b5f78bd4b4617b14a/WindowsTerminal_hf2eZHL0f4.png


想请教一下大概是哪里出现了问题？服务器系统是debian12。
以及还想请教一下程序支持输出详细log吗？

**Comment by zhifengle** [comment]
新建一个 rss2cloud.sh 文件，添加执行权限。
```bash
#!/bin/bash
cd "$(dirname "$0")"
/root/rss2cloud/rss2cloud >> /root/rss2cloud/logfile.log 2>&1
```
定时任务改成执行  /root/rss2cloud/rss2cloud.sh

两次报错的原因都是运行目录的问题。定时任务运行时的目录不是  rss2cloud 二进制文件的目录，所以找不到 .cookies 文件和  `rss.json` 文件

crontab 也可以这样写
`* 8 * * * cd /root/rss2cloud && ./rss2cloud`

**Comment by Volundio** [comment]
> 新建一个 rss2cloud.sh 文件，添加执行权限。
> 
> ```shell
> #!/bin/bash
> cd "$(dirname "$0")"
> /root/rss2cloud/rss2cloud >> /root/rss2cloud/logfile.log 2>&1
> ```
> 
> 定时任务改成执行 /root/rss2cloud/rss2cloud.sh
> 
> 两次报错的原因都是运行目录的问题。定时任务运行时的目录不是 rss2cloud 二进制文件的目录，所以找不到 .cookies 文件和 `rss.json` 文件
> 
> crontab 也可以这样写 `* 8 * * * cd /root/rss2cloud && ./rss2cloud`

感谢指导，已解决！
