### ISSUE TITLE
RSS的数量多了会出现unknown site:  mikanime.me

### ISSUE THREAD

**Issue by Nahuimi** [zhifengle/rss2cloud#4]
![Uploading 3.png…]()

**Comment by Nahuimi** [comment]
破案了，是其中的一个连接出问题了，连接出问题的时候，能不能加个提示，我是一个一个打开排除了

**Comment by zhifengle** [comment]
截图挂了。
提示  unknown site: mikanime.me 。指的是域名 ”mikanime.me“ 不在项目已经支持的网站列表里。

"mikanani.me", "mikanime.tv"  才是正确的蜜柑域名

**Comment by Nahuimi** [comment]
> 截图挂了。 提示 unknown site: mikanime.me 。指的是域名 ”mikanime.me“ 不在项目已经支持的网站列表里。
> 
> "mikanani.me", "mikanime.tv" 才是正确的蜜柑域名

是的，应该弄的时候，不知道怎么弄错了

**Comment by zhifengle** [comment]
> > 截图挂了。 提示 unknown site: mikanime.me 。指的是域名 ”mikanime.me“ 不在项目已经支持的网站列表里。
> > "mikanani.me", "mikanime.tv" 才是正确的蜜柑域名
> 
> 是的，应该弄的时候，不知道怎么弄错了

我优化一下打印的日志，把错误的 RSS 地址也打印出来。
