### ISSUE TITLE
希望可以支持domp4规则

### ISSUE THREAD

**Issue by chanho0** [zhifengle/rss2cloud#5]
背景：现支持的网站对国漫更新速度欠佳，遍寻全网发现domp4更新速率非常快，提供磁力可离线115
但domp4不提供官方RSS，所幸RSSHUB提供支持
![image](https://github.com/zhifengle/rss2cloud/assets/53634547/4b183726-9ac9-4926-bd07-8d783c3e09de)
以凡人修仙传举例，Rsshub链接：https://rsshub.app/domp4/detail/9DvTT8bbbbb8
链接内直接提供磁力
![image](https://github.com/zhifengle/rss2cloud/assets/53634547/b32c142a-918c-4f60-8fdb-3988a2da4bdc)
希望得到作者的支持，感谢

**Comment by zhifengle** [comment]
注意 rsshub.app 不能直连
